version: '3'
services:
  ns-todo-backend:
    container_name: ns-todo-backend-prod
    image: ns-todo-backend:0.0.1-SNAPSHOT
#    build:
#      context: ./todo-backend
#      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING.PROFILES.ACTIVE=prod
  ns-todo-frontend:
    container_name: ns-todo-frontend-prod
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile.prod
#    image: ns-todo-frontend-prod:0.0.1-SNAPSHOT
    ports:
      - "8081:80"
    links:
      - ns-todo-backend