version: '3'
services:
  ns-todo-backend:
    container_name: ns-todo-backend
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING.PROFILES.ACTIVE=dev
  ns-todo-frontend:
    container_name: ns-todo-frontend
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links:
      - ns-todo-backend