spring:
  profiles:
    active: ${ENV:dev}
  application:
    name: coding-assignment
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:tododb
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true


logging:
  level:
    org.hibernate.sql: INFO
    ca.ns.assignment: DEBUG

management:
  endpoint:
    info:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include:
          - health
          - info
          - loggers
          - openapi
          - swagger-ui
    enabled-by-default: true

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  show-actuator: true